// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	maps\animated_models\foliage_desertbrush_1::main();
	common_scripts\_destructible_types_anim_generator::main();
	
	//precachemodel( "viewmodel_desert_eagle" );
	precachemodel( "com_metal_briefcase" );
	precachemodel( "com_cellphone_on" );
	precachemodel( "electronics_pda" );
	precachemodel( "rope_test" );
	precacheshader( "credits_side_bar" );
	
}
